function c = initshape()
%% To initialize structure 'Shape'

measBuff = struct('extrapolated',     [], ...
                  'real_length',      [],...
                  'occurences',       [],... 
                  'whichsubject',      0,...
                  'sizeWISEminsigma',  0,...
                  'locExactshapelet',  0,...
                  'isLeader',0); 
c = measBuff;
end